
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[313] =
    {   0,
        0,    0,    0,    0,   63,   62,    3,    2,   25,   62,
       62,   22,    9,   62,   27,   28,   20,   18,   51,   19,
       62,   21,   45,   44,    1,   12,    4,   13,   52,   52,
       29,   30,    8,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   31,    7,   32,   26,
       56,   55,   56,    0,   25,    0,    0,   22,    9,    0,
       27,   28,   20,   18,   51,   19,    0,   21,   45,   44,
        1,   12,    4,   13,   52,   52,   29,   30,    8,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   31,    7,   32,   26,   25,   11,    0,   48,

        0,    0,   22,    9,    6,    0,    0,   27,   28,   20,
       18,   23,   51,   19,   24,   46,   21,   53,   57,   45,
       46,   44,    1,   12,   17,   15,    4,   10,   13,   14,
       16,   52,   52,   52,   52,   52,   29,   30,    8,   52,
       52,   52,   52,   52,   39,   52,   52,   52,   33,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   31,    7,
        5,   32,   26,   54,   11,    0,    0,    0,    0,    0,
        6,   47,   47,    0,    0,    0,    0,   23,   24,   46,
       57,   57,   46,   17,   15,   10,   14,   16,   52,   52,
       52,   52,   52,   52,   39,   52,   52,   52,   40,   33,

       50,   52,   52,   52,   52,   52,   52,   52,   52,    5,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   49,
       52,   36,   52,   52,   52,   52,   34,   52,   40,   50,
       52,   52,   52,   52,   52,   52,    0,    0,    0,    0,
        0,    0,    0,    0,   49,   42,   36,   52,   52,   52,
       34,   52,   52,   52,   52,   38,    0,    0,    0,    0,
        0,   42,   52,   52,   41,   35,   52,   38,    0,    0,
        0,    0,    0,   52,   37,   41,   35,   52,    0,    0,
        0,    0,    0,   43,   37,    0,    0,    0,    0,   43,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   60,    0,   58,   61,
       59,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   27,   27,
       28,   28,   28,   28,   28,   29,   28,   30,   28,   28,
       28,   28,   28,   28,   31,   28,   28,   28,   28,   28,
       32,   33,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   28,   46,   47,   48,   49,
       50,   51,   28,   52,   53,   54,   55,   56,   57,   58,
       28,   28,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    2,    3,    2,    1,    1,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        1,    1,    1,    1,    1,    1,    5,    2,    2,    2,
        2,    1,    1,    1,    1,    2,    5,    5,    5,    5,
        5,    5,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[320] =
    {   0,
        0,    0,   60,   61,  558, 1319,   73, 1319,  134,   66,
      493,   63,   67,  508,   64,  135,  138,  139,  142,  143,
      129,  148,  152,  153,  158,  161,  166,  171,  172,  178,
      175,  179,  184,  185,  197,  208,  174,  156,  176,  188,
      185,  206,  209,  211,  220,  225,  232,  237,  238,  261,
     1319, 1319,  511,    0,  269,  145,  475,  270,  274,  461,
      275,  278,  282,  285,  286,  290,  248,  294,  298,  299,
      303,  306,  307,  312,  276,  288,  319,  320,  331,  290,
      302,    0,  306,  311,  316,  320,  328,  330,  331,  340,
      342,  350,  340,  347,  381,  389,  393,  394,  161, 1319,

      402,  439,  397,  400,  401,  449,  455,  407,  411,  412,
      415,  416,  420,  421,  425,  428,  432, 1319,  448,  451,
      460,  464,  465,  468,  469,  473,  474,  480,  481,  485,
      496,  497,  501,  458,  475,  477,  513,  514,  518,  487,
      486,  496,  498,  501,  530,  512,  513,  516,  550,  527,
      539,  542,  547,  558,  561,  566,  570,  580,  557,  568,
      571,  619,  624, 1319,  625,  603,  612,  618,  642,  409,
      631, 1319,  435,  285,  648,  672,  678,  638,  639,  642,
      661,  662,  674,  668,  669,  698,  699,  702,  692,  687,
      689,  688,  691,  706,  744,  714,  716,  717,  745,  761,

      766,  734,  725,  735,  744,  746,  754,  765,  764,  772,
      689,  793,  799,  836,  398,  363,  845,  861,  416,  887,
      807,  888,  808,  860,  871,  869,  891,  817,  819,  820,
      870,  886,  902,  905,  910,  920,  404,  939,  948,  985,
      358,  349,  994, 1010,  823, 1036,  844,  957, 1009,  958,
      845,  966, 1017,  919, 1021, 1037, 1056, 1065,  308, 1081,
     1090,  864, 1089, 1018, 1109, 1110, 1099,  892, 1131,  457,
     1062, 1137,  331, 1111, 1161,  907,  925, 1143, 1162, 1182,
      278,  241, 1187, 1193,  946, 1212,  230,  235, 1221,  969,
     1237,  199,  190, 1246,  549,  180,  158,  192,  123,  970,

      994, 1041,  389, 1075,  400,   64, 1319,   28, 1319, 1319,
     1319, 1319, 1288, 1293, 1298, 1302, 1307, 1311, 1313
    } ;

static const flex_int16_t yy_def[320] =
    {   0,
      312,    1,  313,  313,  312,  312,  312,  312,  312,  314,
      312,  312,  312,  315,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  316,  316,
      312,  312,  312,  316,  316,  316,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,  312,  312,  312,  312,
      312,  312,  312,    7,  312,  314,  312,  312,  312,  315,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,   36,   36,  312,  312,  312,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,  312,  312,  312,  312,  312,  312,  314,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  317,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  318,   36,   36,   36,  312,  312,  312,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,  312,  312,
      312,  312,  312,  312,  312,  314,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      317,  317,  312,  312,  312,  312,  312,  312,   36,   36,
       36,   36,   36,   36,  312,   36,   36,   36,   36,  312,

       36,   36,   36,   36,   36,   36,   36,   36,   36,  312,
      314,  312,  312,  314,  312,  312,  312,  312,  319,   36,
       36,   36,   36,   36,   36,   36,   36,   36,  312,  312,
       36,   36,   36,   36,   36,   36,  314,  312,  312,  314,
      312,  312,  312,  312,  312,   36,  312,   36,   36,   36,
      312,   36,   36,   36,   36,   36,  312,  312,  312,  312,
      312,  312,   36,   36,   36,   36,   36,  312,  312,  314,
      312,  312,  312,   36,   36,  312,  312,   36,  312,  312,
      312,  312,  312,   36,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  314,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,    0,  312,  312,  312,  312,  312,  312,  312
    } ;

static const flex_int16_t yy_nxt[1382] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   23,
       24,   25,   26,   27,   28,    6,   29,   29,   29,   30,
       29,   31,    6,   32,   33,   34,   29,   35,   36,   37,
       38,   39,   29,   29,   40,   29,   41,   29,   29,   29,
       29,   42,   43,   29,   44,   45,   46,   29,   47,   48,
       49,   50,   52,   52,  103,  108,  103,  108,  104,  311,
      104,  100,   53,   53,   54,  105,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   69,   70,   71,   72,   73,   74,  101,   75,

       75,   75,   76,   75,   77,  310,   78,   79,   80,   75,
       81,   82,   83,   84,   85,   75,   75,   86,   75,   87,
       75,   75,   75,   75,   88,   89,   75,   90,   91,   92,
       75,   93,   94,   95,   96,   97,  109,   97,  109,  110,
      111,  110,  111,  113,  114,  113,  114,  116,  116,  117,
      100,  117,  112,  120,  122,  120,  122,   98,  115,  123,
      118,  123,  124,  301,  124,  119,  100,  127,  121,  127,
       69,   69,  129,  132,  129,  132,  137,  101,  137,  132,
      138,  132,  138,  125,  126,  139,  132,  139,  132,  128,
      133,  133,  134,  101,  130,  131,  133,  133,  132,  134,

      132,  172,  146,  133,  133,  134,  300,  135,  136,  132,
      134,  132,  134,  135,  144,  133,  133,  134,  299,  134,
      135,  134,  147,  145,  134,  148,  133,  133,  134,  149,
      297,  134,  135,  159,  151,  159,  150,  134,  160,  162,
      160,  162,  134,  135,  141,  134,  152,  134,  140,  134,
      296,  142,  153,  154,  134,  134,  134,  143,  134,  156,
      134,  134,  163,  134,  163,  155,  116,  116,  158,  157,
       97,  103,   97,  103,  134,  104,  108,  104,  108,  109,
      293,  109,  105,  110,  292,  110,  111,  113,  111,  113,
      288,  114,   98,  114,  172,  117,  161,  117,  112,  120,

      122,  120,  122,  216,  123,  115,  123,  124,  127,  124,
      127,  119,  134,  129,  121,  129,   69,   69,  136,  134,
      137,  138,  137,  138,  134,  134,  134,  287,  125,  126,
      128,  134,  139,  134,  139,  130,  131,  134,  134,  134,
      172,  159,  134,  159,  271,  134,  144,  134,  160,  134,
      160,  134,  134,  140,  134,  145,  134,  146,  172,  134,
      134,  149,  147,  134,  134,  148,  134,  134,  150,  134,
      152,  134,  172,  134,  153,  154,  134,  151,  134,  134,
      134,  242,  162,  134,  162,  134,  134,  155,  156,  134,
      163,  157,  163,  158,   97,  165,   97,  165,  103,  134,

      103,  104,  171,  104,  171,  259,  161,   99,  108,  100,
      108,   99,  109,  110,  109,  110,  111,  178,  111,  178,
      166,  113,  114,  113,  114,  172,  179,   99,  179,  180,
      306,  180,  167,  117,   99,  117,  101,  307,   99,   99,
      241,  308,   99,   99,  172,  215,  116,  116,  309,  182,
       99,  182,  120,   99,  120,   99,  168,   99,  172,  169,
      106,  180,  100,  180,  173,  122,  123,  122,  123,  124,
      184,  124,  184,  174,  185,  127,  185,  127,  183,  183,
      106,  186,  129,  186,  129,  175,  187,  106,  187,  101,
      170,  106,  106,  107,  134,  106,  106,  188,  132,  188,

      132,  134,  132,  106,  132,  189,  106,  134,  106,  176,
      106,  134,  177,  134,  137,  138,  137,  138,  134,  139,
      134,  139,  134,  134,  134,  102,  134,  190,  164,  134,
      134,  195,  192,  195,  134,  134,  134,  134,  191,  134,
      107,  134,  194,  102,  134,  134,  193,  134,  134,  134,
      134,  200,  134,  200,  100,  134,  134,  312,  159,  134,
      159,  134,  198,  134,  197,  134,  134,  199,  312,  160,
      134,  160,  210,  134,  210,  134,  134,  312,  134,  134,
      201,  101,  134,  134,  196,  134,  134,  202,  134,  312,
      134,  134,  312,  134,  134,  203,  204,  134,  312,  134,

      205,  134,  134,  312,  134,  206,  134,  134,  100,  134,
      134,  312,  312,  134,  208,  134,  134,  312,  207,  134,
      162,  211,  162,  134,  209,  163,  165,  163,  165,  134,
      212,  212,  171,  312,  171,  101,  213,  213,  212,  178,
      179,  178,  179,  180,  213,  180,  312,  312,  212,  212,
      212,  212,  212,  212,  213,  213,  213,  213,  213,  213,
      214,  214,  182,  182,  182,  182,  217,  217,  214,  184,
      185,  184,  185,  312,  217,  180,  312,  180,  214,  214,
      214,  214,  214,  214,  217,  217,  217,  217,  217,  217,
      218,  218,  183,  183,  100,  312,  219,  219,  218,  186,

      187,  186,  187,  188,  219,  188,  312,  237,  218,  218,
      218,  218,  218,  218,  219,  219,  219,  219,  219,  219,
      220,  101,  312,  221,  134,  134,  312,  134,  134,  222,
      134,  134,  134,  312,  134,  134,  134,  134,  134,  201,
      134,  134,  225,  223,  224,  195,  229,  195,  229,  134,
      134,  226,  134,  228,  312,  134,  227,  134,  312,  134,
      134,  134,  200,  134,  200,  134,  134,  230,  134,  230,
      134,  134,  312,  210,  134,  210,  201,  134,  134,  231,
      134,  134,  134,  134,  134,  312,  232,  134,  134,  134,
      134,  312,  233,  134,  134,  134,  312,  134,  235,  234,

      134,  134,  134,  134,  201,  312,  312,  134,  134,  134,
      236,  238,  238,  134,  134,  134,  312,  239,  239,  238,
      229,  230,  229,  230,  245,  239,  245,  312,  312,  238,
      238,  238,  238,  238,  238,  239,  239,  239,  239,  239,
      239,  100,  312,  134,  134,  247,  251,  247,  251,  312,
      134,  134,  246,  134,  240,  240,  134,  134,  312,  312,
      134,  201,  240,  243,  243,  262,  134,  262,  101,  312,
      201,  243,  240,  240,  240,  240,  240,  240,  312,  244,
      244,  243,  243,  243,  243,  243,  243,  244,  245,  247,
      245,  247,  251,  268,  251,  268,  134,  244,  244,  244,

      244,  244,  244,  134,  248,  134,  134,  134,  276,  134,
      276,  312,  134,  134,  134,  250,  312,  312,  134,  134,
      134,  252,  134,  134,  134,  249,  277,  134,  277,  134,
      134,  134,  312,  312,  134,  134,  134,  134,  134,  201,
      134,  134,  253,  254,  312,  134,  134,  285,  134,  285,
      312,  134,  255,  134,  134,  134,  134,  257,  257,  134,
      256,  312,  266,  134,  312,  257,  258,  258,  134,  134,
      290,  302,  290,  302,  258,  257,  257,  257,  257,  257,
      257,  312,  312,  312,  258,  258,  258,  258,  258,  258,
      100,  312,  312,  134,  134,  304,  312,  304,  201,  312,

      134,  134,  134,  240,  240,  263,  134,  134,  312,  134,
      312,  240,  260,  260,  265,  134,  312,  101,  312,  303,
      260,  240,  240,  240,  240,  240,  240,  312,  261,  261,
      260,  260,  260,  260,  260,  260,  261,  262,  268,  262,
      268,  312,  302,  305,  302,  134,  261,  261,  261,  261,
      261,  261,  134,  134,  134,  264,  201,  134,  134,  312,
      134,  134,  312,  280,  134,  280,  134,  134,  312,  267,
      134,  275,  134,  134,  269,  269,  304,  312,  304,  134,
      134,  312,  269,  270,  270,  134,  134,  312,  312,  312,
      303,  270,  269,  269,  269,  269,  269,  269,  312,  272,

      272,  270,  270,  270,  270,  270,  270,  272,  273,  273,
      276,  277,  276,  277,  281,  282,  273,  272,  272,  272,
      272,  272,  272,  312,  305,  134,  273,  273,  273,  273,
      273,  273,  134,  312,  312,  134,  312,  312,  134,  278,
      312,  312,  134,  274,  312,  134,  134,  134,  134,  279,
      279,  284,  134,  134,  134,  283,  283,  279,  134,  134,
      134,  312,  285,  283,  285,  312,  312,  279,  279,  279,
      279,  279,  279,  283,  283,  283,  283,  283,  283,  134,
      286,  286,  201,  280,  312,  280,  134,  312,  286,  312,
      312,  312,  134,  312,  290,  312,  290,  134,  286,  286,

      286,  286,  286,  286,  134,  289,  289,  312,  312,  312,
      134,  312,  312,  289,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  289,  289,  289,  289,  289,  289,  134,
      291,  291,  312,  312,  281,  282,  134,  312,  291,  294,
      294,  312,  134,  312,  312,  312,  312,  294,  291,  291,
      291,  291,  291,  291,  312,  295,  295,  294,  294,  294,
      294,  294,  294,  295,  298,  298,  312,  312,  312,  312,
      312,  312,  298,  295,  295,  295,  295,  295,  295,  312,
      312,  312,  298,  298,  298,  298,  298,  298,   51,   51,
       51,   51,   51,   99,   99,   99,   99,   99,  106,  106,

      312,  106,  106,  134,  312,  312,  134,  181,  181,  312,
      181,  181,  133,  312,  312,  133,  219,  219,    5,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312
    } ;

static const flex_int16_t yy_chk[1382] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,   12,   15,   12,   15,   13,  308,
       13,   10,    3,    4,    7,   13,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,   10,    7,

        7,    7,    7,    7,    7,  306,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    9,   16,    9,   16,   17,
       18,   17,   18,   19,   20,   19,   20,   21,   21,   22,
       56,   22,   18,   23,   24,   23,   24,    9,   20,   25,
       22,   25,   26,  299,   26,   22,   99,   27,   23,   27,
       23,   23,   28,   29,   28,   29,   31,   56,   31,   30,
       32,   30,   32,   26,   26,   33,   34,   33,   34,   27,
       29,   29,   38,   99,   28,   28,   30,   30,   35,   38,

       35,  298,   38,   34,   34,   38,  297,   29,   30,   36,
       37,   36,   39,   30,   37,   35,   35,   37,  296,   39,
       34,   41,   39,   37,   40,   39,   36,   36,   41,   40,
      293,   40,   35,   47,   41,   47,   40,   40,   48,   49,
       48,   49,   42,   36,   36,   43,   42,   44,   35,   42,
      292,   36,   43,   43,   44,   42,   45,   36,   43,   44,
       44,   46,   50,   45,   50,   43,   67,   67,   46,   45,
       55,   58,   55,   58,   46,   59,   61,   59,   61,   62,
      288,   62,   59,   63,  287,   63,   64,   65,   64,   65,
      282,   66,   55,   66,  174,   68,   48,   68,   64,   69,

       70,   69,   70,  174,   71,   66,   71,   72,   73,   72,
       73,   68,   75,   74,   69,   74,   69,   69,   76,   75,
       77,   78,   77,   78,   76,   75,   80,  281,   72,   72,
       73,   76,   79,   80,   79,   74,   74,   76,   81,   80,
      273,   93,   83,   93,  259,   81,   83,   84,   94,   83,
       94,   81,   85,   81,   84,   83,   86,   84,  242,   85,
       84,   86,   85,   86,   87,   85,   88,   89,   86,   86,
       88,   87,  216,   88,   89,   89,   90,   87,   91,   88,
       89,  216,   95,   90,   95,   91,   92,   89,   90,   90,
       96,   91,   96,   92,   97,   98,   97,   98,  103,   92,

      103,  104,  105,  104,  105,  241,   94,  101,  108,  237,
      108,  101,  109,  110,  109,  110,  111,  112,  111,  112,
      101,  113,  114,  113,  114,  219,  115,  101,  115,  116,
      303,  116,  101,  117,  101,  117,  237,  303,  101,  101,
      215,  305,  101,  101,  173,  170,  116,  116,  305,  119,
      101,  119,  120,  101,  120,  101,  101,  101,  106,  101,
      107,  121,  270,  121,  107,  122,  123,  122,  123,  124,
      125,  124,  125,  107,  126,  127,  126,  127,  121,  121,
      107,  128,  129,  128,  129,  107,  130,  107,  130,  270,
      102,  107,  107,   60,  134,  107,  107,  131,  132,  131,

      132,  134,  133,  107,  133,  136,  107,  134,  107,  107,
      107,  135,  107,  136,  137,  138,  137,  138,  135,  139,
      136,  139,  141,  140,  135,   57,  136,  140,   53,  141,
      140,  145,  142,  145,  143,  141,  140,  144,  141,  142,
       14,  143,  144,   11,  144,  142,  143,  143,  146,  147,
      144,  149,  148,  149,  295,  146,  147,    5,  159,  148,
      159,  146,  147,  150,  146,  148,  145,  148,    0,  160,
      150,  160,  161,  145,  161,  151,  150,    0,  152,  145,
      150,  295,  151,  153,  145,  152,  149,  151,  151,    0,
      153,  152,    0,  149,  154,  152,  153,  155,    0,  149,

      154,  154,  156,    0,  155,  155,  157,  154,  166,  156,
      155,    0,    0,  157,  157,  156,  158,    0,  156,  157,
      162,  166,  162,  158,  158,  163,  165,  163,  165,  158,
      167,  167,  171,    0,  171,  166,  168,  168,  167,  178,
      179,  178,  179,  180,  168,  180,    0,    0,  167,  167,
      167,  167,  167,  167,  168,  168,  168,  168,  168,  168,
      169,  169,  181,  182,  181,  182,  175,  175,  169,  184,
      185,  184,  185,    0,  175,  183,    0,  183,  169,  169,
      169,  169,  169,  169,  175,  175,  175,  175,  175,  175,
      176,  176,  183,  183,  211,    0,  177,  177,  176,  186,

      187,  186,  187,  188,  177,  188,    0,  211,  176,  176,
      176,  176,  176,  176,  177,  177,  177,  177,  177,  177,
      189,  211,    0,  190,  192,  191,    0,  193,  189,  191,
      190,  192,  191,    0,  193,  189,  190,  192,  191,  192,
      193,  189,  194,  193,  193,  195,  199,  195,  199,  194,
      196,  196,  197,  198,    0,  194,  197,  196,    0,  197,
      198,  203,  200,  196,  200,  197,  198,  201,  203,  201,
      202,  204,    0,  210,  203,  210,  202,  202,  204,  203,
      205,  199,  206,  202,  204,    0,  204,  205,  199,  206,
      207,    0,  205,  205,  199,  206,    0,  207,  207,  206,

      209,  208,  201,  207,  208,    0,    0,  209,  208,  201,
      209,  212,  212,  209,  208,  201,    0,  213,  213,  212,
      229,  230,  229,  230,  245,  213,  245,    0,    0,  212,
      212,  212,  212,  212,  212,  213,  213,  213,  213,  213,
      213,  214,    0,  221,  223,  247,  251,  247,  251,    0,
      221,  223,  221,  228,  214,  214,  221,  223,    0,    0,
      228,  223,  214,  217,  217,  262,  228,  262,  214,    0,
      228,  217,  214,  214,  214,  214,  214,  214,    0,  218,
      218,  217,  217,  217,  217,  217,  217,  218,  220,  222,
      220,  222,  227,  268,  227,  268,  224,  218,  218,  218,

      218,  218,  218,  224,  224,  226,  231,  225,  276,  224,
      276,    0,  226,  231,  225,  226,    0,    0,  226,  231,
      225,  231,  232,  220,  222,  225,  277,  227,  277,  232,
      220,  222,    0,    0,  227,  232,  220,  222,  233,  232,
      227,  234,  233,  234,    0,  233,  235,  285,  234,  285,
        0,  233,  235,  235,  234,  254,  236,  238,  238,  235,
      236,    0,  254,  236,    0,  238,  239,  239,  254,  236,
      290,  300,  290,  300,  239,  238,  238,  238,  238,  238,
      238,    0,    0,    0,  239,  239,  239,  239,  239,  239,
      240,    0,    0,  248,  250,  301,    0,  301,  250,    0,

      248,  250,  252,  240,  240,  248,  248,  250,    0,  252,
        0,  240,  243,  243,  252,  252,    0,  240,    0,  300,
      243,  240,  240,  240,  240,  240,  240,    0,  244,  244,
      243,  243,  243,  243,  243,  243,  244,  246,  256,  246,
      256,    0,  302,  301,  302,  249,  244,  244,  244,  244,
      244,  244,  249,  253,  264,  249,  253,  255,  249,    0,
      253,  264,    0,  271,  255,  271,  253,  264,    0,  255,
      255,  264,  246,  256,  257,  257,  304,    0,  304,  246,
      256,    0,  257,  258,  258,  246,  256,    0,    0,    0,
      302,  258,  257,  257,  257,  257,  257,  257,    0,  260,

      260,  258,  258,  258,  258,  258,  258,  260,  261,  261,
      265,  266,  265,  266,  271,  271,  261,  260,  260,  260,
      260,  260,  260,    0,  304,  263,  261,  261,  261,  261,
      261,  261,  263,    0,    0,  267,    0,    0,  263,  267,
        0,    0,  267,  263,    0,  265,  266,  274,  267,  269,
      269,  274,  265,  266,  274,  272,  272,  269,  265,  266,
      274,    0,  275,  272,  275,    0,    0,  269,  269,  269,
      269,  269,  269,  272,  272,  272,  272,  272,  272,  278,
      279,  279,  278,  280,    0,  280,  278,    0,  279,    0,
        0,    0,  278,    0,  284,    0,  284,  275,  279,  279,

      279,  279,  279,  279,  275,  283,  283,    0,    0,    0,
      275,    0,    0,  283,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  283,  283,  283,  283,  283,  283,  284,
      286,  286,    0,    0,  280,  280,  284,    0,  286,  289,
      289,    0,  284,    0,    0,    0,    0,  289,  286,  286,
      286,  286,  286,  286,    0,  291,  291,  289,  289,  289,
      289,  289,  289,  291,  294,  294,    0,    0,    0,    0,
        0,    0,  294,  291,  291,  291,  291,  291,  291,    0,
        0,    0,  294,  294,  294,  294,  294,  294,  313,  313,
      313,  313,  313,  314,  314,  314,  314,  314,  315,  315,

        0,  315,  315,  316,    0,    0,  316,  317,  317,    0,
      317,  317,  318,    0,    0,  318,  319,  319,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
extern "C" int yylex();
#include <iostream>
#include <cstring>
#include <sstream>
#include "y.tab.h"

using namespace std;

bool committing = false;

char* word(char* str, int len, int str_or_char = 0) {
    // cout << "received: '" << str << "' length: " << len << endl;
    char* wanted = new char[len + 1]();

    if (str_or_char == 0) {
        str = strtok(str, " \t");
        while (str != NULL) {
            strcat(wanted, str);
            str = strtok(NULL, " \t");
        }
    }
    else if (str_or_char == 1) {
        for (int i = 0; i < len; i ++) {
            if (str[i] != '"')
                continue;

            strcat(wanted, &str[i]);
            break;
        }
    }
    else {
        for (int i = 0; i < len; i ++) {
            if (str[i] != '\'')
                continue;
            
            strcat(wanted, &str[i]);
            break;
        }
    }

    strcat(wanted, "\0");    
    // cout << "pass to parser: '" << wanted << "'" << endl;
    return wanted;
}
#line 896 "lex.yy.c"

#line 898 "lex.yy.c"

#define INITIAL 0
#define COMMENT_START 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 62 "scanner.l"


#line 1119 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 313 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1319 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 64 "scanner.l"
{ yylval.str = word(yytext, yyleng); return ';'; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 65 "scanner.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 66 "scanner.l"
{}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 68 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '='; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 69 "scanner.l"
{ yylval.str = word(yytext, yyleng); return OR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 70 "scanner.l"
{ yylval.str = word(yytext, yyleng); return AND; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 71 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '|'; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 72 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '^'; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '&'; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 74 "scanner.l"
{ yylval.str = word(yytext, yyleng); return EQUAL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 75 "scanner.l"
{ yylval.str = word(yytext, yyleng); return NOT_EQUAL; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '<'; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 77 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '>'; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "scanner.l"
{ yylval.str = word(yytext, yyleng); return GE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 79 "scanner.l"
{ yylval.str = word(yytext, yyleng); return LE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 80 "scanner.l"
{ yylval.str = word(yytext, yyleng); return RS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 81 "scanner.l"
{ yylval.str = word(yytext, yyleng); return LS; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 82 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '+'; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 83 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '-'; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 84 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '*'; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 85 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '/'; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 86 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '%'; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 87 "scanner.l"
{ yylval.str = word(yytext, yyleng); return INC; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "scanner.l"
{ yylval.str = word(yytext, yyleng); return DEC; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 89 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '!'; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 90 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '~'; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 91 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '('; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 92 "scanner.l"
{ yylval.str = word(yytext, yyleng); return ')'; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 93 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '['; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 94 "scanner.l"
{ yylval.str = word(yytext, yyleng); return ']'; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 95 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '{'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "scanner.l"
{ yylval.str = word(yytext, yyleng); return '}'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 98 "scanner.l"
{ yylval.str = word(yytext, yyleng); return IF; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 99 "scanner.l"
{ yylval.str = word(yytext, yyleng); return ELSE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 100 "scanner.l"
{ yylval.str = word(yytext, yyleng); return SWITCH; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 101 "scanner.l"
{ yylval.str = word(yytext, yyleng); return CASE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 102 "scanner.l"
{ yylval.str = word(yytext, yyleng); return DEFAULT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 103 "scanner.l"
{ yylval.str = word(yytext, yyleng); return WHILE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 104 "scanner.l"
{ yylval.str = word(yytext, yyleng); return DO; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 105 "scanner.l"
{ yylval.str = word(yytext, yyleng); return FOR; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "scanner.l"
{ yylval.str = word(yytext, yyleng); return RETURN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 107 "scanner.l"
{ yylval.str = word(yytext, yyleng); return BREAK; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 108 "scanner.l"
{ yylval.str = word(yytext, yyleng); return CONTINUE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 110 "scanner.l"
{ yylval.str = word(yytext, yyleng); return ':'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 112 "scanner.l"
{ sprintf(yylval.str, "%d", atoi(word(yytext, yyleng))); return INT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 113 "scanner.l"
{ sprintf(yylval.str, "%f", atof(word(yytext, yyleng))); return FLOAT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 114 "scanner.l"
{ yylval.str = word(yytext, yyleng, 2); return CHAR; }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 115 "scanner.l"
{ yylval.str = word(yytext, yyleng, 1); return STR; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 116 "scanner.l"
{ yylval.str = word(yytext, yyleng); return Null; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 118 "scanner.l"
{ yylval.str = word(yytext, yyleng); return TYPE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 119 "scanner.l"
{ yylval.str = word(yytext, yyleng); return ','; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 120 "scanner.l"
{ yylval.str = word(yytext, yyleng); return ID; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 122 "scanner.l"
{
    BEGIN COMMENT_START;
    committing = true;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 126 "scanner.l"
{
    if (committing) {
        BEGIN 0;
        committing = false;
    }
}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 132 "scanner.l"
{}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 133 "scanner.l"
{}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 134 "scanner.l"
{}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 135 "scanner.l"
{}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 136 "scanner.l"
{}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 137 "scanner.l"
{}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 138 "scanner.l"
{}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 139 "scanner.l"
ECHO;
	YY_BREAK
#line 1497 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_START):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 313 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 313 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 312);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 139 "scanner.l"

